### ISSUE TITLE
"cudaErrorPeerAccessAlreadyEnabled" when running DLRM with Terabyte dataset

### ISSUE THREAD

**Issue by TimJZ** [facebookresearch/dlrm#161] opened 2021-02-20 20:56 UTC
Hi, I'm currently trying to run DLRM with binary format of the preprocessed terabyte dataset with 4 GPUs, but I've been getting the following errors: 

```
/mnt/dlrm/data_loader_terabyte.py:229: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  ../torch/csrc/utils/tensor_numpy.cpp:137.)
  tensor = torch.from_numpy(array).view((-1, self.tot_fea))
Traceback (most recent call last):
  File "dlrm_s_pytorch.py", line 1868, in <module>
    run()
  File "dlrm_s_pytorch.py", line 1524, in run
    t1 = time_wrap(use_gpu)
  File "dlrm_s_pytorch.py", line 116, in time_wrap
    torch.cuda.synchronize()
  File "/opt/conda/lib/python3.8/site-packages/torch/cuda/__init__.py", line 380, in synchronize
    return torch._C._cuda_synchronize()
RuntimeError: CUDA error: device-side assert triggered
/tmp/pip-req-build-2fnmqrq2/aten/src/ATen/native/cuda/Indexing.cu:385: indexAddLargeIndex: block: [528,0,0], thread: [96,0,0] Assertion `dstIndex < dstAddDimSize` failed.
/tmp/pip-req-build-2fnmqrq2/aten/src/ATen/native/cuda/Indexing.cu:385: indexAddLargeIndex: block: [528,0,0], thread: [97,0,0] Assertion `dstIndex < dstAddDimSize` failed.
/tmp/pip-req-build-2fnmqrq2/aten/src/ATen/native/cuda/Indexing.cu:385: indexAddLargeIndex: block: [528,0,0], thread: [98,0,0] Assertion `dstIndex < dstAddDimSize` failed.
/tmp/pip-req-build-2fnmqrq2/aten/src/ATen/native/cuda/Indexing.cu:385: indexAddLargeIndex: block: [528,0,0], thread: [99,0,0] Assertion `dstIndex < dstAddDimSize` failed.
/tmp/pip-req-build-2fnmqrq2/aten/src/ATen/native/cuda/Indexing.cu:385: indexAddLargeIndex: block: [528,0,0], thread: [100,0,0] Assertion `dstIndex < dstAddDimSize` failed.
/tmp/pip-req-build-2fnmqrq2/aten/src/ATen/native/cuda/Indexing.cu:385: indexAddLargeIndex: block: [528,0,0], thread: [101,0,0] Assertion `dstIndex < dstAddDimSize` failed.
/tmp/pip-req-build-2fnmqrq2/aten/src/ATen/native/cuda/Indexing.cu:385: indexAddLargeIndex: block: [528,0,0], thread: [102,0,0] Assertion `dstIndex < dstAddDimSize` failed.
/tmp/pip-req-build-2fnmqrq2/aten/src/ATen/native/cuda/Indexing.cu:385: indexAddLargeIndex: block: [528,0,0], thread: [103,0,0] Assertion `dstIndex < dstAddDimSize` failed.
/tmp/pip-req-build-2fnmqrq2/aten/src/ATen/native/cuda/Indexing.cu:385: indexAddLargeIndex: block: [528,0,0], thread: [104,0,0] Assertion `dstIndex < dstAddDimSize` failed.
/tmp/pip-req-build-2fnmqrq2/aten/src/ATen/native/cuda/Indexing.cu:385: indexAddLargeIndex: block: [528,0,0], thread: [105,0,0] Assertion `dstIndex < dstAddDimSize` failed.
/tmp/pip-req-build-2fnmqrq2/aten/src/ATen/native/cuda/Indexing.cu:385: indexAddLargeIndex: block: [528,0,0], thread: [106,0,0] Assertion `dstIndex < dstAddDimSize` failed.
/tmp/pip-req-build-2fnmqrq2/aten/src/ATen/native/cuda/Indexing.cu:385: indexAddLargeIndex: block: [528,0,0], thread: [107,0,0] Assertion `dstIndex < dstAddDimSize` failed.
/tmp/pip-req-build-2fnmqrq2/aten/src/ATen/native/cuda/Indexing.cu:385: indexAddLargeIndex: block: [528,0,0], thread: [108,0,0] Assertion `dstIndex < dstAddDimSize` failed.
/tmp/pip-req-build-2fnmqrq2/aten/src/ATen/native/cuda/Indexing.cu:385: indexAddLargeIndex: block: [528,0,0], thread: [109,0,0] Assertion `dstIndex < dstAddDimSize` failed.
/tmp/pip-req-build-2fnmqrq2/aten/src/ATen/native/cuda/Indexing.cu:385: indexAddLargeIndex: block: [528,0,0], thread: [110,0,0] Assertion `dstIndex < dstAddDimSize` failed.
/tmp/pip-req-build-2fnmqrq2/aten/src/ATen/native/cuda/Indexing.cu:385: indexAddLargeIndex: block: [528,0,0], thread: [111,0,0] Assertion `dstIndex < dstAddDimSize` failed.
/tmp/pip-req-build-2fnmqrq2/aten/src/ATen/native/cuda/Indexing.cu:385: indexAddLargeIndex: block: [528,0,0], thread: [112,0,0] Assertion `dstIndex < dstAddDimSize` failed.
/tmp/pip-req-build-2fnmqrq2/aten/src/ATen/native/cuda/Indexing.cu:385: indexAddLargeIndex: block: [528,0,0], thread: [113,0,0] Assertion `dstIndex < dstAddDimSize` failed.
/tmp/pip-req-build-2fnmqrq2/aten/src/ATen/native/cuda/Indexing.cu:385: indexAddLargeIndex: block: [528,0,0], thread: [114,0,0] Assertion `dstIndex < dstAddDimSize` failed.
/tmp/pip-req-build-2fnmqrq2/aten/src/ATen/native/cuda/Indexing.cu:385: indexAddLargeIndex: block: [528,0,0], thread: [115,0,0] Assertion `dstIndex < dstAddDimSize` failed.
/tmp/pip-req-build-2fnmqrq2/aten/src/ATen/native/cuda/Indexing.cu:385: indexAddLargeIndex: block: [528,0,0], thread: [116,0,0] Assertion `dstIndex < dstAddDimSize` failed.
/tmp/pip-req-build-2fnmqrq2/aten/src/ATen/native/cuda/Indexing.cu:385: indexAddLargeIndex: block: [528,0,0], thread: [117,0,0] Assertion `dstIndex < dstAddDimSize` failed.
/tmp/pip-req-build-2fnmqrq2/aten/src/ATen/native/cuda/Indexing.cu:385: indexAddLargeIndex: block: [528,0,0], thread: [118,0,0] Assertion `dstIndex < dstAddDimSize` failed.
/tmp/pip-req-build-2fnmqrq2/aten/src/ATen/native/cuda/Indexing.cu:385: indexAddLargeIndex: block: [528,0,0], thread: [119,0,0] Assertion `dstIndex < dstAddDimSize` failed.
/tmp/pip-req-build-2fnmqrq2/aten/src/ATen/native/cuda/Indexing.cu:385: indexAddLargeIndex: block: [528,0,0], thread: [120,0,0] Assertion `dstIndex < dstAddDimSize` failed.
/tmp/pip-req-build-2fnmqrq2/aten/src/ATen/native/cuda/Indexing.cu:385: indexAddLargeIndex: block: [528,0,0], thread: [121,0,0] Assertion `dstIndex < dstAddDimSize` failed.
/tmp/pip-req-build-2fnmqrq2/aten/src/ATen/native/cuda/Indexing.cu:385: indexAddLargeIndex: block: [528,0,0], thread: [122,0,0] Assertion `dstIndex < dstAddDimSize` failed.
/tmp/pip-req-build-2fnmqrq2/aten/src/ATen/native/cuda/Indexing.cu:385: indexAddLargeIndex: block: [528,0,0], thread: [123,0,0] Assertion `dstIndex < dstAddDimSize` failed.
/tmp/pip-req-build-2fnmqrq2/aten/src/ATen/native/cuda/Indexing.cu:385: indexAddLargeIndex: block: [528,0,0], thread: [124,0,0] Assertion `dstIndex < dstAddDimSize` failed.
/tmp/pip-req-build-2fnmqrq2/aten/src/ATen/native/cuda/Indexing.cu:385: indexAddLargeIndex: block: [528,0,0], thread: [125,0,0] Assertion `dstIndex < dstAddDimSize` failed.
/tmp/pip-req-build-2fnmqrq2/aten/src/ATen/native/cuda/Indexing.cu:385: indexAddLargeIndex: block: [528,0,0], thread: [126,0,0] Assertion `dstIndex < dstAddDimSize` failed.
/tmp/pip-req-build-2fnmqrq2/aten/src/ATen/native/cuda/Indexing.cu:385: indexAddLargeIndex: block: [528,0,0], thread: [127,0,0] Assertion `dstIndex < dstAddDimSize` failed.
/tmp/pip-req-build-2fnmqrq2/aten/src/ATen/native/cuda/Indexing.cu:385: indexAddLargeIndex: block: [528,0,0], thread: [64,0,0] Assertion `dstIndex < dstAddDimSize` failed.
/tmp/pip-req-build-2fnmqrq2/aten/src/ATen/native/cuda/Indexing.cu:385: indexAddLargeIndex: block: [528,0,0], thread: [65,0,0] Assertion `dstIndex < dstAddDimSize` failed.
/tmp/pip-req-build-2fnmqrq2/aten/src/ATen/native/cuda/Indexing.cu:385: indexAddLargeIndex: block: [528,0,0], thread: [66,0,0] Assertion `dstIndex < dstAddDimSize` failed.
/tmp/pip-req-build-2fnmqrq2/aten/src/ATen/native/cuda/Indexing.cu:385: indexAddLargeIndex: block: [528,0,0], thread: [67,0,0] Assertion `dstIndex < dstAddDimSize` failed.
/tmp/pip-req-build-2fnmqrq2/aten/src/ATen/native/cuda/Indexing.cu:385: indexAddLargeIndex: block: [528,0,0], thread: [68,0,0] Assertion `dstIndex < dstAddDimSize` failed.
/tmp/pip-req-build-2fnmqrq2/aten/src/ATen/native/cuda/Indexing.cu:385: indexAddLargeIndex: block: [528,0,0], thread: [69,0,0] Assertion `dstIndex < dstAddDimSize` failed.
/tmp/pip-req-build-2fnmqrq2/aten/src/ATen/native/cuda/Indexing.cu:385: indexAddLargeIndex: block: [528,0,0], thread: [70,0,0] Assertion `dstIndex < dstAddDimSize` failed.
/tmp/pip-req-build-2fnmqrq2/aten/src/ATen/native/cuda/Indexing.cu:385: indexAddLargeIndex: block: [528,0,0], thread: [71,0,0] Assertion `dstIndex < dstAddDimSize` failed.
/tmp/pip-req-build-2fnmqrq2/aten/src/ATen/native/cuda/Indexing.cu:385: indexAddLargeIndex: block: [528,0,0], thread: [72,0,0] Assertion `dstIndex < dstAddDimSize` failed.
/tmp/pip-req-build-2fnmqrq2/aten/src/ATen/native/cuda/Indexing.cu:385: indexAddLargeIndex: block: [528,0,0], thread: [73,0,0] Assertion `dstIndex < dstAddDimSize` failed.
/tmp/pip-req-build-2fnmqrq2/aten/src/ATen/native/cuda/Indexing.cu:385: indexAddLargeIndex: block: [528,0,0], thread: [74,0,0] Assertion `dstIndex < dstAddDimSize` failed.
/tmp/pip-req-build-2fnmqrq2/aten/src/ATen/native/cuda/Indexing.cu:385: indexAddLargeIndex: block: [528,0,0], thread: [75,0,0] Assertion `dstIndex < dstAddDimSize` failed.
/tmp/pip-req-build-2fnmqrq2/aten/src/ATen/native/cuda/Indexing.cu:385: indexAddLargeIndex: block: [528,0,0], thread: [76,0,0] Assertion `dstIndex < dstAddDimSize` failed.
/tmp/pip-req-build-2fnmqrq2/aten/src/ATen/native/cuda/Indexing.cu:385: indexAddLargeIndex: block: [528,0,0], thread: [77,0,0] Assertion `dstIndex < dstAddDimSize` failed.
/tmp/pip-req-build-2fnmqrq2/aten/src/ATen/native/cuda/Indexing.cu:385: indexAddLargeIndex: block: [528,0,0], thread: [78,0,0] Assertion `dstIndex < dstAddDimSize` failed.
/tmp/pip-req-build-2fnmqrq2/aten/src/ATen/native/cuda/Indexing.cu:385: indexAddLargeIndex: block: [528,0,0], thread: [79,0,0] Assertion `dstIndex < dstAddDimSize` failed.
/tmp/pip-req-build-2fnmqrq2/aten/src/ATen/native/cuda/Indexing.cu:385: indexAddLargeIndex: block: [528,0,0], thread: [80,0,0] Assertion `dstIndex < dstAddDimSize` failed.
/tmp/pip-req-build-2fnmqrq2/aten/src/ATen/native/cuda/Indexing.cu:385: indexAddLargeIndex: block: [528,0,0], thread: [81,0,0] Assertion `dstIndex < dstAddDimSize` failed.
/tmp/pip-req-build-2fnmqrq2/aten/src/ATen/native/cuda/Indexing.cu:385: indexAddLargeIndex: block: [528,0,0], thread: [82,0,0] Assertion `dstIndex < dstAddDimSize` failed.
/tmp/pip-req-build-2fnmqrq2/aten/src/ATen/native/cuda/Indexing.cu:385: indexAddLargeIndex: block: [528,0,0], thread: [83,0,0] Assertion `dstIndex < dstAddDimSize` failed.
/tmp/pip-req-build-2fnmqrq2/aten/src/ATen/native/cuda/Indexing.cu:385: indexAddLargeIndex: block: [528,0,0], thread: [84,0,0] Assertion `dstIndex < dstAddDimSize` failed.
/tmp/pip-req-build-2fnmqrq2/aten/src/ATen/native/cuda/Indexing.cu:385: indexAddLargeIndex: block: [528,0,0], thread: [85,0,0] Assertion `dstIndex < dstAddDimSize` failed.
/tmp/pip-req-build-2fnmqrq2/aten/src/ATen/native/cuda/Indexing.cu:385: indexAddLargeIndex: block: [528,0,0], thread: [86,0,0] Assertion `dstIndex < dstAddDimSize` failed.
/tmp/pip-req-build-2fnmqrq2/aten/src/ATen/native/cuda/Indexing.cu:385: indexAddLargeIndex: block: [528,0,0], thread: [87,0,0] Assertion `dstIndex < dstAddDimSize` failed.
/tmp/pip-req-build-2fnmqrq2/aten/src/ATen/native/cuda/Indexing.cu:385: indexAddLargeIndex: block: [528,0,0], thread: [88,0,0] Assertion `dstIndex < dstAddDimSize` failed.
/tmp/pip-req-build-2fnmqrq2/aten/src/ATen/native/cuda/Indexing.cu:385: indexAddLargeIndex: block: [528,0,0], thread: [89,0,0] Assertion `dstIndex < dstAddDimSize` failed.
/tmp/pip-req-build-2fnmqrq2/aten/src/ATen/native/cuda/Indexing.cu:385: indexAddLargeIndex: block: [528,0,0], thread: [90,0,0] Assertion `dstIndex < dstAddDimSize` failed.
/tmp/pip-req-build-2fnmqrq2/aten/src/ATen/native/cuda/Indexing.cu:385: indexAddLargeIndex: block: [528,0,0], thread: [91,0,0] Assertion `dstIndex < dstAddDimSize` failed.
/tmp/pip-req-build-2fnmqrq2/aten/src/ATen/native/cuda/Indexing.cu:385: indexAddLargeIndex: block: [528,0,0], thread: [92,0,0] Assertion `dstIndex < dstAddDimSize` failed.
/tmp/pip-req-build-2fnmqrq2/aten/src/ATen/native/cuda/Indexing.cu:385: indexAddLargeIndex: block: [528,0,0], thread: [93,0,0] Assertion `dstIndex < dstAddDimSize` failed.
/tmp/pip-req-build-2fnmqrq2/aten/src/ATen/native/cuda/Indexing.cu:385: indexAddLargeIndex: block: [528,0,0], thread: [94,0,0] Assertion `dstIndex < dstAddDimSize` failed.
/tmp/pip-req-build-2fnmqrq2/aten/src/ATen/native/cuda/Indexing.cu:385: indexAddLargeIndex: block: [528,0,0], thread: [95,0,0] Assertion `dstIndex < dstAddDimSize` failed.
done
```

When I'm trying to run it with cuda-memcheck, I constantly get errors like 

```
========= Program hit cudaErrorPeerAccessAlreadyEnabled (error 704) due to "peer access is already enabled" on CUDA API call to cudaDeviceEnablePeerAccess.
=========     Saved host backtrace up to driver entry point at error
=========     Host Frame:/usr/local/cuda/compat/lib/libcuda.so.1 [0x3343d3]
=========     Host Frame:/usr/lib/x86_64-linux-gnu/libnccl.so.2 [0xd56e4]
=========     Host Frame:/usr/lib/x86_64-linux-gnu/libnccl.so.2 [0x4f1c7]
=========     Host Frame:/usr/lib/x86_64-linux-gnu/libnccl.so.2 [0x4352a]
=========     Host Frame:/usr/lib/x86_64-linux-gnu/libnccl.so.2 [0x34430]
=========     Host Frame:/usr/lib/x86_64-linux-gnu/libnccl.so.2 [0x34d25]
=========     Host Frame:/usr/lib/x86_64-linux-gnu/libnccl.so.2 [0x46ca7]
=========     Host Frame:/usr/lib/x86_64-linux-gnu/libpthread.so.0 [0x9609]
=========     Host Frame:/usr/lib/x86_64-linux-gnu/libc.so.6 (clone + 0x43) [0x122293]
```

I'm wondering if anyone else has seen an issue like this when running the code. I'd really appreciate it if someone could provide some help on this issue. Could this be an error due to the incorrect setups of the enviornment or parameters? Or is it more of an error resulted from the dataset? Thanks! 

The shell script I was using is attached below:
 
```
$dlrm_pt_bin --arch-sparse-feature-size=64 --arch-mlp-bot="13-512-256-64" --arch-mlp-top="512-512-256-1" --max-ind-range=10000000 --data-generation=dataset --data-set=terabyte --raw-data-file=/dataset/binary/day --processed-data-file=/dataset/binary/terabyte_processed --loss-function=bce --round-targets=True --learning-rate=0.1 --mini-batch-size=2048 --print-freq=1024 --print-time --test-mini-batch-size=16384 --test-num-workers=16 --use-gpu --memory-map  --mlperf-bin-loader  $dlrm_extra_option 2>&1
```

**Comment by mnaumovfb** [comment] 2021-02-21 18:52
Can you try running without using `--num-workers` or `--test-num-workers=16` parameters? They are not compatible with `--memory-map` flag. Let me know if it works.

**Comment by TimJZ** [comment] 2021-02-26 23:25
Thank you very much for your response! However, currently the only avalible dataset form me is the binary form of terabyte dataset. Therefore I'm not able to run the default command. In my previous trails, I've tried the script with the mlperf-logging and other options with --mlperf-bin-loader option, but I was still getting the same issue.

**Comment by dkorchevgithub** [comment] 2021-03-04 19:30
So far, we could not reproduce your bug. You can generate a small random terabyte or Kaggle data set using this script https://github.com/mlcommons/inference/blob/master/recommendation/dlrm/pytorch/tools/make_fake_criteo.sh. 

Please try it with this data set to make sure your setup/CUDA/drivers are working correctly. 

For example, to generate terabyte data run:
./make_fake_criteo.sh terabyte

The data will be in text format and you can use them to to see if training works on your system.

Please let us know the results.

**Comment by TimJZ** [comment] 2021-03-20 18:03
I've recently noticed some strange behaviors: when I'm using the pytorch version 1.6.0a0+9907a3e, the code was able to run with no problem. However, when I'm trying to migrate it to a new environment with pytorch vertsion 1.8.0a0+1606899 (docker image pytorch:20.12-py3), I'm getting the above errors. I'm wondering if anyone has run into the same issue as I do. Thanks!

**Comment by mnaumovfb** [comment] 2021-06-27 22:53
I don't believe we have seen the issue with different PyTorch versions. Is this gone or still there?

**Comment by mnaumovfb** [comment] 2021-09-03 05:10
We have not heard back for a long time. I'm assuming this is resolved. Closing.

**Closed by mnaumovfb** 2021-09-03 05:10 UTC
